services:
  postgres:
    image: postgres:13
    env_file:
      - .env
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d middleware_dev']
      interval: 10s
      timeout: 5s
      retries: 5
  #   volumes:
  #     - pg_data:/var/lib/postgresql/data

  # pgweb:
  #   image: sosedoff/pgweb
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   ports:
  #     - '5433:8081'
  #   env_file:
  #     - .env
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ['CMD-SHELL', 'wget -qO- http://localhost:8081/ || exit 1']
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: managements_api
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - ./uploads:/app/uploads
    command: ['node', 'dist/index.js']

volumes:
  pg_data:
