apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "deploy-component.fullname" $ }}
  labels:
    {{- include "deploy-component.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "deploy-component.labels.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "deploy-component.labels.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "deploy-component.name" $ }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
{{- if or (and .Values.app.envs (gt (len .Values.app.envs) 0)) (and .Values.secrets (gt (len .Values.secrets) 0)) }}
          env:
          {{- range $key, $value := .Values.app.envs }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
          {{- range $key, $value := .Values.secrets }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "deploy-component.fullname" $ }}
                  key: {{ $key }}
          {{- end }}
{{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
#            - name: metrics
#              containerPort: 9113
          # ... resto de la configuración del contenedor ...
{{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: app-data-volume
              mountPath: /data  # Ajusta esta ruta según las necesidades de tu aplicación
      volumes:
        - name: app-data-volume
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "deploy-component.fullname" .) }}
{{- end }}