{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "deploy-component.fullname" . }}
  annotations:
    # Anotaciones para el AWS Load Balancer Controller
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.ingress.hostname | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "deploy-component.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
          # No permitir acceso a /metrics desde el ALB
          - path: /metrics
            pathType: Prefix
            backend:
              service:
                name: non-existent-service
                port:
                  number: 9999
{{- end }}