{{- if .Values.observability.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "deploy-component.fullname" . }}
  labels:
    # Esta etiqueta es importante para que Prometheus descubra este ServiceMonitor
    release: prometheus
spec:
  selector:
    matchLabels:
      # Debe coincidir con la etiqueta del Service que creamos
      app: {{ include "deploy-component.name" . }}
  endpoints:
  - port: http # El nombre del puerto de métricas en el Service, se usa el mismo nombre que el Service principal 'http'
    interval: 60s
    path: /metrics # La ruta donde tu app expone las métricas
{{- end }}